language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
cache:
  directories:
    - node_modules
notifications:
  email:       false
after_success:
  - firebase deploy --project bjurado-com --token $FIREBASE_TOKEN
