name: Check Format
on:
  push:
  pull_request:
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.6

      - name: Install 🔧 # Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Check Format
        run: |
          bun run check-format
